server:
  port: 8090
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org:
      springframework: ERROR

spring:
  ai:
    openai:
      api-key: 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
  application:
    name: course-service

  data:
    mongodb:
      username: admin
      password: admin
      authentication-database: admin
      host: 46.8.29.63
      port: 27019
      repositories:
        enabled: true


spring.kafka:
  bootstrap-servers: 127.0.0.1:39092, 127.0.0.1:29092
  consumer:
    key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"
  producer:
    key-serializer: org.apache.kafka.common.serialization.LongSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


token:
  iam: t1.9euelZrKnJzOnMfOyY-Ti4uWypaVme3rnpWamJ6Jy8_KzI-eyZaLkpvLxozl9PcjG05F-e85aHOG3fT3Y0lLRfnvOWhzhs3n9euelZqczZWTyMeKx5fHkY3LysyJi-_8xeuelZqczZWTyMeKx5fHkY3LysyJiw.909vTZo7X07IBwsaItqAM5_8Iv929JcWpl-KvCVhZ55uNDx9YBQHr1GrLrlmmh8bk8mQTDwbCg41ncbVLWmyCA
  folderId: b1gebvniis9kf6dhlm57