version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: file-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    command: mongod --port 27018
    ports:
      - '27018:27018'
