services:
  db_user:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: "postgrespw"
      POSTGRES_USER: "postgres"
    expose:
      - "5432"
    command: -p 5432
    ports:
      - "5432:5432"